### ISSUE TITLE
 Ad is currently warming up. Please try again in a few minutes

### ISSUE THREAD

**Issue by JohnnyTseng** [mopub/mopub-ios-sdk#123]
Hi, I'm using MoPub SDK 3.6.0 for iOS, but facing an issue,
My ad unit is Native ad, and I created this ad few weeks ago,
But sometimes shows message: "[ad unit id] is currently warming up. Please try again in a few minutes"
I don't know why this message will show, and cant find any reference for this message.

My app is in production, I think this issue may affect requests of my ad, Could you please check this issue?

I've sent the ad unit id to:support@mopub.com
Thanks

**Comment by alicerp** [comment]
From https://twittercommunity.com/t/why-doesnt-my-ad-unit-work-on-the-first-request/21986:

"Our ad server requires ad units to warm up before being able to deliver an ad.

As our ad server has a large number of servers each of these have to be warmed up for a particular ad unit in order for everyone to have ads deliver properly. Since each user is divided up by ad servers randomly, it takes a nominal number to make sure that every server is warmed up.

When your app is live, this issue shouldn't occur.

Additionally, newly created ad units will be automatically warmed up for all ad servers."

Additional information: https://twittercommunity.com/t/i-m-not-getting-ads-and-my-log-cat-log-device-console-logs-are-outputting-this-message-mopub-banner-ad-view-is-fetching-ad-network-type-clear-what-does-this-mean-and-how-do-i-fix-this/37693
