### ISSUE TITLE
[NativeAds] Native ads are showing only in the 1st section

### ISSUE THREAD

**Issue by D6mi** [mopub/mopub-ios-sdk#126]
Hi, 

Is it possible to enable Mopub to render the native ads in all of the TableView sections, using the rule set on the Dashboard?

Best regards,
D6mi

**Comment by alicerp** [comment]
Hi D6mi--

By "Dashboard" do you mean the native location control in the UI (https://dev.twitter.com/mopub/ui/native-location-control)?

For additional questions, feel free to check out https://twittercommunity.com/c/fabric/mopub or email support@mopub.com.

**Comment by D6mi** [comment]
Hi, Alice,

On the provided link, the image displaying the Control's not available so let me put this in words. By Dashboard I mean the part of the MoPub configuration portal where you can set the interval of occurrence for ads.

Best regards,
Domagoj

**Comment by alicerp** [comment]
Hi Domagoj--

You cannot set 1 as the frequency, otherwise ads would show in every position.

Please note that the MoPub Github Issue Reporting Section will now be housed directly on the Twitter Developer Community Forum.

Please visit https://twittercommunity.com/c/fabric/mopub for any additional support questions or feel free to email suport@mopub.com.

Thank you for your patience and understanding.

Alice
