### ISSUE TITLE
Call loadRewardedVideoAdWithAdUnitID:withMediationSettings: from background thread produce "UI API called from background thread" warning

### ISSUE THREAD

**Issue by cunzhegao** [mopub/mopub-ios-sdk#258]
I tried to call load loadRewardedVideoAdWithAdUnitID:withMediationSettings:, and Xcode complain that inside MPAdServerURLBuilder, when constructing URL queryParams, Mopub SDK tried to get device orientation using [UIApplication sharedApplication].statusBarOrientation. Is this expected or i'm not suppose to call load video from non main thread?

- [√ ] I am submitting a bug report for existing functionality
- [√ ] I visited https://developers.mopub.com/ and found no answer
- [√] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [√ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.5.0
#### Device model and OS Version:
iPhone X， 12.0
#### Xcode Version:
10.1
#### Ad Unit IDs used in reproducing the issue:
Any Ad Unit ID
#### Steps to reproduce the behavior:
loadRewardedVideoAdWithAdUnitID:withMediationSettings: from background thread
#### Expected behavior:
no warning 
#### Observed behavior:
Xcode complain about UI API called from background thread.

**Comment by chauduyphanvu1** [comment]
@cunzhegao - thanks for letting us know about that warning. I've synced with the rest of the team, and we'll see what we can do to rectify it. We'll let you know when the fix is deployed to production. The ideal scenario is you should be able to call `loadRewardedVideoAdWithAdUnitID:withMediationSettings:` on a background thread without seeing that warning as a result of the SDK making calls to `[UIApplication sharedApplication].statusBarOrientation`.

Vu Chau
MoPub SDK Team

**Comment by chauduyphanvu** [comment]
@cunzhegao, this has been fixed in the 5.8.0 iOS SDK release. Check it out and let us know if you still see the issue!
