### ISSUE TITLE
MoPub SDK Initialisation Load

### ISSUE THREAD

**Issue by Taher-17** [mopub/mopub-ios-sdk#311]
One line summary of the issue here

The MoPub SDK does not get initialised

- [YES ] I am submitting a bug report for existing functionality
- [YES ] I visited https://developers.mopub.com/ and found no answer
- [YES ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [YES ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.10.0

#### Device model and OS Version:
iPhone X, iOS 13.3.1 Beta 2 & 13.3.1 Beta 1

#### Xcode Version:
Xcode 11.0 & 11.3

#### Ad Unit IDs used in reproducing the issue:
`2d6ca79a89a346628de6835b4ab644b9`

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

1. Installed Pods with mediation: `pod 'GoogleMobileAdsMediationMoPub'`
2. Initialise with code below in didFinishLaunching
3. CompletionHandler not called and app is frozen.

```
let sdk = MPMoPubConfiguration.init(adUnitIdForAppInitialization: AdUnits.mopubInterstitial)
MoPub.sharedInstance().initializeSdk(with: sdk) { [weak self] in
                guard let self = self else { return }
                self.mpInterstitial = MPInterstitialAdController(forAdUnitId: AdUnits.mopubInterstitial)
                self.mpInterstitial?.delegate = self
                MPRewardedVideo.setDelegate(self, forAdUnitId: AdUnits.mopubVideo)
}
```
The completionHandler is never called, all requests from the app then fail (Cloudfirestore)

#### Expected behavior:
As concisely as possible, describe the expected behavior.

The SDK should call the completion handler and continue with the flow 

#### Observed behavior:
As concisely as possible, describe the observed behavior.

CompletionHandler not called.

#### Evidence:
Device log files, Network log file, etc.

N/A

**Comment by Taher-17** [comment]
UPDATE: moving the initialisation to the FIRST call after didFinishLaunching resolved this issue - I believe it still needs investigation

**Comment by chauduyphanvu** [comment]
@Taher-17, since you're using `pod 'GoogleMobileAdsMediationMoPub'`, the Mobile Ads SDK from Google will handle initializing the MoPub SDK [via the adapters](https://github.com/googleads/googleads-mobile-ios-mediation/blob/01f5ba0640a3509a3ed3acf3188d3a1c3549e38f/adapters/MoPub/MoPubAdapter/GADMAdapterMoPubSingleton.m#L36-L53). As a result, you do not have to initialize the MoPub SDK in your app (you could, but you shouldn't be instantiating MoPub ad objects, like `MPInterstitialAdController`, from your app).

Initializing the MoPub SDK from your app AND calling MoPub APIs (you are supposed to let the Mobile Ads SDK handle calls to mediation SDKs) directly from your app is not a desired practice, and might have resulted in an infinite loop that caused your app to freeze.

Going forward, ensure you do either one of the following two options:

* Skip initializing MoPub from your app. This means you should do nothing related to MoPub. The adapters will take care of all calls on your behalf (code linked above).
* Initialize MoPub from your app but don't call any other MoPub APIs. The adapters will [skip the MoPub initialization](https://github.com/googleads/googleads-mobile-ios-mediation/blob/master/adapters/MoPub/MoPubAdapter/GADMAdapterMoPubSingleton.m#L38-L41).

Let us know if you have any questions!

Vu Chau
MoPub Team

**Comment by Taher-17** [comment]
@chauduyphanvu Hey, thanks for the clarification. I was following this guide: https://developers.google.com/admob/ios/mediation/mopub which says that we should initialise the SDK.

**Comment by chauduyphanvu** [comment]
@Taher-17, yes, in that case you can follow the second bullet from my suggestion:

> Initialize MoPub from your app but don't call any other MoPub APIs. The adapters will skip the MoPub initialization.

**Comment by Taher-17** [comment]
@chauduyphanvu awesome, thank you. 
Closing this issue.

**Comment by shinwan2** [comment]
My team recently found this issue as well. If you choose this option
> Initialize MoPub from your app but don't call any other MoPub APIs. The adapters will skip the MoPub initialization.

then you need to make sure to initialize MoPub **before** calling `GADMobileAds.startWithCompletionHandler` (it's already documented [here](https://developers.google.com/admob/ios/api/reference/Classes/GADMobileAds#/c:objc(cs)GADMobileAds(im)startWithCompletionHandler:)).
> Calls completionHandler when the GMA SDK and all mediation networks are fully set up or if set-up times out. 

Otherwise there's a risk of deadlock. This stack trace below shows Thread1 and Thread8 are blocking each other from initializing MoPub.

```
Thread 1 Queue : com.apple.main-thread (serial)Thread 1 Queue : com.apple.main-thread (serial)#0 0x00007fff523b79be 
    in __ulock_wait ()#1 0x00000001147856ac 
    in _dlock_wait ()#2 0x000000011478562b 
    in _dispatch_once_wait ()#3 0x000000010ff3be37 
    in _dispatch_once [inlined] at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include/dispatch/once.h:84#4 0x000000010ff3bdf8 
    in -[MoPub initializeSdkWithConfiguration:completion:] at /{myProjectDir}/Pods/mopub-ios-sdk/MoPubSDK/MoPub.m:115#5 0x000000010c91ef44 
    in -[AppDelegate application:didFinishLaunchingWithOptions:] at /{myProjectDir}/AppDelegate/AppDelegate.m:113#7 0x00007fff48089ad8 
    in -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] ()#8 0x00007fff4808b460 
    in -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] ()#9 0x00007fff48090f05 
    in -[UIApplication _runWithMainScene:transitionContext:completion:] ()#10 0x00007fff477c576d 
    in -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] ()#11 0x00007fff47cb44c1 
    in _UIScenePerformActionsWithLifecycleActionMask ()#12 0x00007fff477c627f

Thread 8 Queue : com.apple.root.utility-qos (concurrent)#0 0x00007fff523b79be 
    in __ulock_wait ()#1 0x00000001147856ac 
    in _dlock_wait ()#2 0x000000011478550b 
    in _dispatch_thread_event_wait_slow ()#3 0x0000000114793d09 
    in __DISPATCH_WAIT_FOR_QUEUE__ ()#4 0x0000000114793766 
    in _dispatch_sync_f_slow ()#5 0x0000000110006d16 
    in +[MPURLRequest userAgent] at /{myProjectDir}/Pods/mopub-ios-sdk/MoPubSDK/internal/MPURLRequest.m:128#6 0x000000011000654a 
    in -[MPURLRequest initWithURL:] at /{myProjectDir}/Pods/mopub-ios-sdk/MoPubSDK/internal/MPURLRequest.m:59#7 0x0000000110006a67 
    in +[MPURLRequest requestWithURL:] at /{myProjectDir}/Pods/mopub-ios-sdk/MoPubSDK/internal/MPURLRequest.m:89#8 0x000000010ff9255d 
    in -[MPConsentManager synchronizeConsentWithCompletion:] at /{myProjectDir}/Pods/mopub-ios-sdk/MoPubSDK/internal/MPConsentManager.m:511#9 0x000000010ff3c3ad 
    in -[MoPub setSdkWithConfiguration:completion:] at /{myProjectDir}/Pods/mopub-ios-sdk/MoPubSDK/MoPub.m:139#10 0x000000010ff3bf01 
    in __51-[MoPub initializeSdkWithConfiguration:completion:]_block_invoke at /{myProjectDir}/Pods/mopub-ios-sdk/MoPubSDK/MoPub.m:116#11 0x0000000114784d48 
    in _dispatch_client_callout ()#12 0x0000000114786297 
    in _dispatch_once_callout ()#13 0x000000010ff3be37 
    in _dispatch_once [inlined] at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include/dispatch/once.h:84#14 0x000000010ff3bdf8 
    in -[MoPub initializeSdkWithConfiguration:completion:] at /{myProjectDir}/Pods/mopub-ios-sdk/MoPubSDK/MoPub.m:115#15 0x000000010d4ec530 
    in -[GADMAdapterMoPubSingleton initializeMoPubSDKWithAdUnitID:completionHandler:] ()#16 0x000000010d4f25a8 
    in +[GADMediationAdapterMoPub setUpWithConfiguration:completionHandler:] ()#17 0x000000010d39c8a2  
```
