### ISSUE TITLE
app use all CPU resources after ad loading

### ISSUE THREAD

**Issue by Pingou** [mopub/mopub-ios-sdk#312]
Cpu usage jumps to 80% and stay there after an interstitial loading

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.10.0

#### Device model and OS Version:
Simulator iOS 13.2.2
#### Xcode Version:
11.2.1
#### Ad Unit IDs used in reproducing the issue:
standard test ad unit

#### Steps to reproduce the behavior:
Launch the sample app, select html interstitial, click "load", watch the CPU usage jump to >80% and never come down.

#### Expected behavior:
CPU usage should stay at 0.

#### Observed behavior:
CPU usage >80%
This bug makes the MoPub library completely unusable.

**Comment by hmertkahraman** [comment]
Hi @Pingou,

Thanks for raising this issue. 

In order to make sure if we understand the issue correctly, for where you mention:
```jump to >80% and never come down```
Can you please clarify for which of the following is the case:
A- Do you dismiss the interstitial with close button, and the memory usage doesn't come down to 0% after dismissing?
B- Do you keep the interstitial alive on the screen, and while the interstitial is visible on the screen the memory usage doesn't come down to 0%?

Thanks,
MoPub Team

**Comment by Pingou** [comment]
Hi @hmertkahraman ,

I do not even display the interstitial, I just load it.
I am not talking about memory usage but processor usage, which drains the battery very fast.

**Comment by hmertkahraman** [comment]
Hi @Pingou ,

Your concern is well received on our end and we will investigate the issue further. Unfortunately we were initially unable to reproduce the issue; the results we get are:

The memory usage jumps to %32 from <%1 once the HTML Interstitial is **opened**, and then comes down to %0 when **dismissed**.

That's why we want to see if we can fully replicate your environment to troubleshoot the issue. Therefore, in order to investigate further, would you be able to provide some more details of your environment:
- Which exact simulator device did you use, and do you observe this on multiple simulators?
- Did you try running the app on an actual device and observe if the same issue happens, can you share the results?
- Would you be able to share details of your Mac device you're using? Specifically it's processor, and RAM details as your simulator is tied to them.
- What happens when you hit Show for the interstitial ad, have it appear, then dismiss it. Can you share how does the CPU usage moves during all this while?

Thanks,
Mert

**Comment by Pingou** [comment]
- I tested with iPhone 11 Pro Max iOS 13.2.2 simulator.
Interestingly, on a real device (iPhone 8, iOS 13), it is not so bad, it just goes to 8% when loading ad and stay there. The console keeps outputing: "[Process] kill() returned unexpected error 1"

- My mac device:
2,3 GHz 8-Core Intel Core i9
32 GB 2667 MHz DDR4

- If I hit show (on the iPhone), usage goes from 8 (after loading) to 10 (showing ad), then goes back to zero when I close it. As soon as I load another one, usage goes back to 8.
On a simulator it is similar, it goes from 0 if I don't do anything, to 80%, when I load the ad, to 100% when displaying it, then to 0 when I close, and back to 80 if I reload another one.

**Comment by hmertkahraman** [comment]
Hi @Pingou ,

Thank you again for providing these details. We will investigate this issue on our end and will get back to you. Meanwhile, if you already integrated MoPub with your own project, that is not our sample app, we would appreciate if you can test it over there to see if the same processor usage spike occurs.

Thanks,
Mert

**Comment by Pingou** [comment]
Thank you @hmertkahraman .
Yes, I have the same issue with my app, that's actually why I tried the sample app, to be sure that it was coming from MoPub.

**Comment by hmertkahraman** [comment]
Hi @Pingou ,

Our investigations are continuing. 

Meanwhile, we also want to request from you, if possible, an Xcode Instruments test that shows the CPU spike when you load ads. Our aim is to gather any useful information for us so that we can narrow down the domain. We'll also be in touch regarding our investigations.

Thanks,
Mert

**Comment by hmertkahraman** [comment]
Hi @Pingou ,

Unfortunately we cannot reproduce the case on our end, despite we have the repro steps from you and target the same application. So checking in with you regarding the latest comment above to be able to help.

Thanks,
Mert

**Comment by Pingou** [comment]
Hi @hmertkahraman,

Sorry for the delay, here is a screenshot, let me know if you need more.

<img width="1153" alt="Screenshot 2020-02-18 at 16 53 01" src="https://user-images.githubusercontent.com/915430/74752682-58a0c480-526f-11ea-9c12-566c23ca6baa.png">

Simulator iPhone 11 Pro, ios 13.2.2

**Comment by hmertkahraman** [comment]
Thanks @Pingou ,

We will investigate these.

Mert

**Comment by hmertkahraman** [comment]
Hi @Pingou ,

We are unfortunately unable to reproduce the issue on our end. I will update this thread if any new developments occur. Meanwhile, if you have any additional material or guidance that can help us, please send over.

Thanks,
Mert
