### ISSUE TITLE
iOS 9 support

### ISSUE THREAD

**Issue by wimbledon** [mopub/mopub-ios-sdk#325]
@chauduyphanvu, can we at least release mopub-ios-sdk SDK version that fixes the UIWebView issue (#313) for iOS 9 before dropping the iOS 9 support?
iOS 9 is still supported on Xcode 11 until the end of the year and all other ad SDKs support iOS 9.0 currently.
Thank you for your consideration.

**Comment by chauduyphanvu** [comment]
@wimbledon, thanks for sharing your feedback with us! We made the decision to move to iOS 10 in 5.13.0 due to a combination of bug fixes and new feature additions that depend on iOS 10, as well as the low traffic on iOS 9 we had been observing internally.

I've relayed your feedback to the rest of the team, but in the meantime we do not have any plans to release a version that removes Moat/IAS (fixing the UIWebView warnings) for iOS 9 specifically. Thanks for your understanding.

Vu Chau
MoPub Team
