### ISSUE TITLE
No native ads on collectionView.mp_insertItems(atIndexPaths:)

### ISSUE THREAD

**Issue by seemayr** [mopub/mopub-ios-sdk#339]
Using `mp_insertItems(atIndexPaths:)` on a UICollectionView **does not insert native ads**.
The only way to add new cells (with automatically inserted native-ads in between) into an already filled UICollectionView is using `mp_reloadData()` for me, which works. Managing ad-placement remotely via MoPub.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.13.1

#### Device model and OS Version:
iPhone XR (14.0)
iPhone X (13.6)
iPhone 6s (13.6)

#### Xcode Version:
12.0 Beta 4 & 11.6

#### Ad Unit IDs used in reproducing the issue:
76a3fefaced247959582d2d2df6f4757 _(Standard Dev. Test Ad Unit ID)_

#### Steps to reproduce the behavior:
- Fill an UICollectionView with some cells so it shows some native ads already.
- Then, use mp_insertItems to insert some more items _(so that it also should insert new native ads)_
- :( -> No native ads inserted. _Right now, native ads will only appear after a full table reload via mp_reloadData()._

**Comment by p158276** [comment]
Hello @seemayr ,
Thank you for putting together the bug report.
The behaviour you are seeing is unintended, we are aware of this issue and are investigating it.
You can check the following two workarounds and see if it works.
1. As AdPlacer is for non-advanced table setups. It is recommended they use Manual integration for this advanced setup.
2. Less optimal but also a workaround is to refresh the table by mp_reloadData. Understood that this is less visually appealing because the table reloads but that is an option.

Yoyo Lin
MoPub Team
