### ISSUE TITLE
MoPub SDK that not initialized on iOS 9 is crashing 

### ISSUE THREAD

**Issue by Bogomol** [mopub/mopub-ios-sdk#350]
Hi. 
We trying to add MoPub SDK in our application and as our app supports iOS 9, MoPub is initializes only for iOS version 10+:
 
```
if (@available(iOS 10, *)) {
    MPMoPubConfiguration *sdkConfig = [[MPMoPubConfiguration alloc] initWithAdUnitIdForAppInitialization:@"920b6145fb1546cf8b5cf2ac34638bb7"];
    sdkConfig.loggingLevel = MPBLogLevelInfo;
    [[MoPub sharedInstance] initializeSdkWithConfiguration:sdkConfig completion:^{
        NSLog(@"MoPub SDK initialization complete");
    }];
}
```
Despite the fact MoPub does not initialize on iOS 9 it crashes(see attached file).
Could you please check it?

#### Evidence:
[iOS9-crash.txt](https://github.com/mopub/mopub-ios-sdk/files/5457009/iOS9-crash.txt)

**Comment by p158276** [comment]
Hi @Bogomol ,
Thanks for reaching out. Our [requirement](https://developers.mopub.com/publishers/ios/integrate/#requirements) after MoPub 5.13 SDK is iOS 10.0 or higher. You can either use the old version SDK prior to 5.13 or decide to change the xcode support to iOS 10.

Yoyo Lin 
MoPub Team

**Comment by Bogomol** [comment]
Thanks for a response.
We do not initialize MoPub on iOS 9 as you can see in my message above. 
If we do not initialize MoPub on iOS 9 why it's crashes in MoPub sources?
And we can't drop iOS 9 for our app.

**Comment by p158276** [comment]
Hi @Bogomol ,
Thanks for the confirmation. 
Could you also check if you called any MoPub related logic other than initialized under iOS 10?

**Comment by Bogomol** [comment]
@p158276 thanks for a reply.
We also do `loadRewardedVideoAdWithAdUnitID`, but it's also has own if statement to check iOS 10 to be available.

**Comment by p158276** [comment]
HI @Bogomol ,

Checking the crashlog, it seems like crash happened when there's an logging attempting to retrieve the ifa. I'll circle back this crash issue back to our internal team. 

In the meantime if you are willing to modify SDK code source, you can try to remove `MPLogInfo(@"%@ error: %@", NSStringFromSelector(_cmd), error);` from `MPWebBrowserUserAgentInfo.m` and see if that fixes the issue.

**Comment by IvanoBilenchi** [comment]
I'm experiencing this issue as well. I understand that the MoPub SDK requires iOS 10 and later, however wrapping all MoPub logic behind appropriate iOS version checks shouldn't crash the app.

In this case, the crash will happen regardless of any iOS version check on our part since `MPWebBrowserUserAgentInfo.m` does stuff in `+ (void)load`, which is always called when the app starts (and which is not a good idea for library code 😅).

A potential fix would be moving that logic to `+ (void)initialize` (and wrapping it in the usual `if (self == [MPWebBrowserUserAgentInfo self]`), though this causes that logic to be called only when the class is referenced in user code (so, not when the app is started). This should work fine though, since I believe the only purpose of that logic is to initialize the `gUserAgent` global, which can be only retrieved via the `+ (NSString *)userAgent` class method (so you need to reference `MPWebBrowserUserAgentInfo` in order to retrieve it, which fires `+ (void)initialize`).

If for some reason you really need that logic to run at app load, please at least wrap all `+ (void)load` calls in appropriate iOS version checks, so that the MoPub library can be used on apps that still support older iOS versions. I will be opting for this solution, though an official fix would be greatly appreciated.

**Comment by p158276** [comment]
Hi @IvanoBilenchi ,
Thanks for the feedback. I am bringing your suggestion back to our engineering team. We'll provide the information when there's any update. Is the workaround you mentioned solve the problem you have?

**Comment by IvanoBilenchi** [comment]
Yes, it fixes the issue, as it ensures no code is ever run on iOS < 10. I'll share my fix, in case you find it useful.

```objc
// I defined this macro in my precompiled headers, as I need to
// keep track of the min supported iOS versions for multiple ad SDKs for my own version checks.

// As a suggestion, you folks may want to do this too (e.g. add a define somewhere in your headers),
// and update other version checks you do throughout the SDK
// (such as in '- (void)initializeSdkWithConfiguration:completion:' (MoPub.m))
// so as to avoid regressions when/if the MoPub SDK drops support for iOS 10.

#define MOPUB_MIN_IOS 10

// Then, in 'MPWebBrowserUserAgentInfo.m':

+ (void)load {
    if (@available(iOS MOPUB_MIN_IOS, *)) {
        // No need for "dispatch once" since `load` is called only once during app launch.
        [self obtainUserAgentFromWebView];
    }
}
```

Thank you for your time and reply.

**Comment by p158276** [comment]
We try to cover all the potential crash for not initialize SDK in v[5.16.0](https://github.com/mopub/mopub-ios-sdk/releases/tag/5.16.0). Let us know if you still encounter any other issue.
