### ISSUE TITLE
Facebook Audience network mediated banners are zero-width

### ISSUE THREAD

**Issue by fulldiver-ilya** [mopub/mopub-ios-sdk#366]
There is some problem with facebook banners width, it's equals zero for some reasons

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Just initialize an SDK configuration with any of valid unit id
Then add (I'm not sure this is required setup step)
```swift
configuration.additionalNetworks = [ FacebookAdapterConfiguration.self ]
configuration.mediatedNetworkConfigurations = [ "FacebookAdapterConfiguration": [:] ]
```
Load `MPAdView` with `loadAdWithMaxAdSize:(CGSize)size`

#### Expected behavior:
I expect to see a Facebook Audience Network banner when Facebook wins mediation bid.

#### Observed behavior:
But I have only empty `MPAdView` with zero-width `FBAdView` inside successfully loaded. And there is no impression event logged.
All MoPub market banners are loaded ok and impressed as expected.

#### Evidence:
<img width="402" alt="Screenshot 2021-02-04 at 09 54 35" src="https://user-images.githubusercontent.com/59820813/106856063-013d7380-66cf-11eb-8c76-bf7ed9b6b875.png">

**Comment by fulldiver-ilya** [comment]
I tried provide an `placement_ids` with adapter configuration — nothing changed, the result is the same
```swift
configuration.mediatedNetworkConfigurations = [ "FacebookAdapterConfiguration": [:] ]
```

The app calls 
```objc
- (void)adViewDidLoad:(FBAdView *)adView
```
at `FacebookBannerCustomEvent` but there is no banner at `MPAdView` anyway

**Comment by fulldiver-ilya** [comment]
I fount that there was inconsistency with width parameter, the best result I achieve is below, but where is a content of banner?
labels? CTA?
<img width="430" alt="Screenshot 2021-02-04 at 13 12 06" src="https://user-images.githubusercontent.com/59820813/106878174-b3ceff80-66ea-11eb-8a5c-0974b5119a34.png">

**Comment by chauduyphanvu** [comment]
@fulldiver-ilya, since you mentioned `MPAdView`, it sounds like you might be using MoPub's banner APIs to request Facebook's native banners. That integration is not supported—you need to request Facebook's native banners via MoPub's native ad APIs. 

See [this page](https://developers.mopub.com/publishers/mediation/networks/facebook/#request-native-banner-ads) for the integration steps to request and serve Facebook's native banners. It's recommended to keep a separate layout for native banners since the ad assets will be fewer, and they can differ in style compared to regular native ads.

Let us know if there are any questions!

Vu Chau
MoPub Team

**Comment by fulldiver-ilya** [comment]
@chauduyphanvu thank you for reply!

I have an easy example snippet:
```swift
import UIKit
import MoPub

class ViewController: UIViewController {
    
    private var adContainer: UIView!
    
    override func loadView() {
        super.loadView()
        
        // Main layout stack
        
        let stack = UIStackView()
        stack.translatesAutoresizingMaskIntoConstraints = false
        
        stack.axis = .vertical
        stack.spacing = 32
        
        view.addSubview(stack)
        NSLayoutConstraint.activate([
            stack.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 8),
            stack.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            stack.trailingAnchor.constraint(equalTo: view.trailingAnchor)
        ])
        
        // Advertisement container
        
        let adContainer = UIView()
        adContainer.backgroundColor = .magenta
        
        stack.addArrangedSubview(adContainer)
        NSLayoutConstraint.activate([
            adContainer.heightAnchor.constraint(equalToConstant: 50)
        ])
        
        self.adContainer = adContainer
        
        // Loading button
        
        let loadButton = UIButton(type: .system)
        loadButton.setTitle("Load", for: .normal)
        loadButton.addTarget(self, action: #selector(loadAction(_:)), for: .touchUpInside)
        
        stack.addArrangedSubview(loadButton)
    }
    
}

extension ViewController {
    
    @objc func loadAction(_ sender: UIButton) {
        self.adContainer.subviews.forEach({ $0.removeFromSuperview() })
        
        guard let banner = MPAdView(adUnitId: <#unit id configured with html banner mediation from facebook#>) else {
            return
        }
        
        banner.translatesAutoresizingMaskIntoConstraints = false
        self.adContainer.addSubview(banner)
        NSLayoutConstraint.activate([
            banner.topAnchor.constraint(equalTo: self.adContainer.topAnchor),
            banner.leadingAnchor.constraint(equalTo: self.adContainer.leadingAnchor),
            banner.trailingAnchor.constraint(equalTo: self.adContainer.trailingAnchor),
            banner.bottomAnchor.constraint(equalTo: self.adContainer.bottomAnchor)
        ])
        
        banner.delegate = self
        banner.loadAd(withMaxAdSize: kMPPresetMaxAdSize50Height)
    }
    
}

extension ViewController: MPAdViewDelegate {
    
    func viewControllerForPresentingModalView() -> UIViewController! {
        return self
    }
    
    func adViewDidLoadAd(_ view: MPAdView!, adSize: CGSize) {
        print(">>> \(#function) -> \(adSize) => \(view.subviews.first.debugDescription)")
    }
    
    func adView(_ view: MPAdView!, didFailToLoadAdWithError error: Error!) {
        print(">>> \(#function) -> \(error.localizedDescription)")
    }
    
}
```

In this case `FBAdView` will be sized `{0; 50}`

When I change code above with that:
```swift
// ...

    private var banner: MPAdView?

// ...
        // Advertisement container
        
        let adContainer = UIView()
        adContainer.backgroundColor = .magenta
        
        stack.addArrangedSubview(adContainer)
        NSLayoutConstraint.activate([
            adContainer.heightAnchor.constraint(equalToConstant: 50)
        ])
        
        if let banner = MPAdView(adUnitId: "<#unit id configured with html banner mediation from facebook#>") {
            banner.translatesAutoresizingMaskIntoConstraints = false
            
            banner.delegate = self
            
            adContainer.addSubview(banner)
            NSLayoutConstraint.activate([
                banner.topAnchor.constraint(equalTo: adContainer.topAnchor),
                banner.leadingAnchor.constraint(equalTo: adContainer.leadingAnchor),
                banner.trailingAnchor.constraint(equalTo: adContainer.trailingAnchor),
                banner.bottomAnchor.constraint(equalTo: adContainer.bottomAnchor)
            ])
            
            self.banner = banner
        }
        
        // Loading button
// ...
```

and then load ads just with 
```swift
        banner?.loadAd(withMaxAdSize: kMPPresetMaxAdSize50Height)
```

the size is correct (for my case `{375;50}`)

The difference as you can see is to not create `MPAdView` before each loading, storing a single instance at the `self` and then reuse it.

But size incorrect only for Facebook Audience Network banners, MoPub marketplace always works fine with both examples above

I will try to change my project code with reusing `MPAdView` but it's interesting to know why it's happens?

**Comment by chauduyphanvu** [comment]
@fulldiver-ilya, it looks like the source of the issue might be due to the fact that `MPAdView` (banner) is used. Facebook's native banners are in fact a flavor of native ads. They are not banner ads. That means you may not use `MPAdView` to make the ad requests.

You must start by implementing the [MoPub native APIs](https://developers.mopub.com/publishers/ios/native-adplacer/). Feel free to reference our [sample app native ad usage](https://github.com/mopub/mopub-ios-sdk/blob/master/Canary/Canary/Formats/NativeAdDataSource.swift).

Then, pass the flag to the mediation adapters to request [Facebook's native banner ads](https://developers.mopub.com/publishers/mediation/networks/facebook/#request-native-banner-ads).

**Comment by fulldiver-ilya** [comment]
I dont request any of native ads with `MPAdView`, Facebook AN configured with **Banner**

<img width="610" alt="Screenshot 2021-02-06 at 07 27 22" src="https://user-images.githubusercontent.com/59820813/107108979-6a4af580-684d-11eb-8a69-1aac1cc040a9.png">

I think the reason of zero-width is that `MPAdView` didn't layout before call `loadAd` with Facebook bid winner.
You could try to reproduce that with my `ViewController` snippets above and configured with Facebook Banner unit_id

Is it true? Or there is some another reasons?

**Comment by chauduyphanvu** [comment]
@fulldiver-ilya, thanks for the research. It's probably having something to do with this specific behavior [here](https://github.com/mopub/mopub-ios-mediation/blob/master/FacebookAudienceNetwork/FacebookBannerCustomEvent.m#L92):

```obj-c
CGRect fbAdFrame = self.fbAdView.frame;
fbAdFrame.size.width = size.width;              // Since FB ad sizes are flexible width, use the container width
fbAdFrame.size.height = fbAdSize.size.height;   // Use the FB ad size height
self.fbAdView.frame = fbAdFrame;
```

Since the adapter is creating a new CGRect taking into account the width of the parent container, when you create your `MPAdView` programmatically and immediately call `loadAd`, there is no data for width to be used. I recommend defining a max ad size before you make the ad request (because the previous size you define is tied to the previous instances of `MPAdView`). 

Let us know if there are any questions.
