### ISSUE TITLE
iPhoneXR safe guides not respected for close button

### ISSUE THREAD

**Issue by franck-nadeau** [mopub/mopub-ios-sdk#380]
One line summary of the issue here

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:

  pod 'mopub-ios-sdk', '~>5.13'

#### Device model and OS Version:

iPhone XR, ios 14

#### Xcode Version:

Version 12.4 (12D4e)

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

1. Watch an add (I believe the offending ads come from MarketPlace)

#### Expected behavior:
As concisely as possible, describe the expected behavior.

1. User should be able to close the ads by pressing on the close button.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

The close button is placed too high, above the safe guides, and the user cannot close the ad.

#### Evidence:
Device log files, Network log file, etc.

![Screen_Shot_2021-03-19_at_11 08 02_AM (1)](https://user-images.githubusercontent.com/2902651/112158185-515c9080-8bbe-11eb-8c87-1de906f638f3.png)
![Screen_Shot_2021-03-19_at_11 08 37_AM](https://user-images.githubusercontent.com/2902651/112158189-51f52700-8bbe-11eb-922c-340ac629e137.png)
![Screen_Shot_2021-03-22_at_9 59 42_AM](https://user-images.githubusercontent.com/2902651/112158191-51f52700-8bbe-11eb-9fac-ab329ef876f8.png)

**Comment by p158276** [comment]
Hi @franck-nadeau ,
Thanks for reaching out. Can you provide the affected MoPub ad unit ID and device log? For the MoPub Marketplace ad, our close button is on the right-top of the screen. You can also tell the network ad by checking the device log. Let us know if you have any questions here.

Yoyo Lin
MoPub Team

**Comment by franck-nadeau** [comment]
Unfortunately, this is only happening in production for us, and I don't have access to the logs.

I made the assumption that it was from Marketplace, since it is clearly not Vungle. We also have Admod integrated.

**Comment by franck-nadeau** [comment]
The affect MoPub ad unit ID is `54753cdc05c14acd9590b55965eecb3b`.

**Comment by p158276** [comment]
Hi @franck-nadeau ,
Thanks for the information. Actually, we don't allow our DSP partner to [customize the close button](https://developers.mopub.com/dsps/ad-formats/mraid/#14-what-are-your-close-button-requirements) since last year. So all of the close buttons should be in the right top corner when it is from Marketplace. 

From the ad unit ID `54753cdc05c14acd9590b55965eecb3b`, it seems you also use [Vungle](https://developers.mopub.com/publishers/mediation/networks/vungle/#additional-support) and [Admob](https://groups.google.com/forum/#!forum/google-admob-ads-sdk/) mediation. I would suggest you can reach out to them and see if it is their ad. 

Besides, you can try to upgrade both MoPub and third-party SDK and adapter to the latest version and see if the problem persists.

**Comment by chenxi141017** [comment]
I have the same problem. Happened in production and unable to reproduce.

**Comment by chauduyphanvu** [comment]
@DiegoAce, thanks for the details. If you aren't using Marketplace but are seeing this issue (with only AdMob), there isn't much we can do from the MoPub side. 

Where you have reached out to AdMob for help? Feel free to try this forum: https://groups.google.com/g/google-admob-ads-sdk. 

Vu Chau
MoPub Team
